In [1]:
import pandas as pd
import numpy as np

# Data load

In [2]:
df1=pd.read_csv('도로교통공단_전국_사망교통사고정보(2018)_20190910.csv',encoding="cp949")
df2=pd.read_csv('도로교통공단_전국사망교통사고_2017.csv',encoding="cp949")
df3=pd.read_csv('2016년_교통사망사고정보.csv',encoding="cp949")
df4=pd.read_csv('도로교통공단_전국_사망교통사고정보(2015)_20190910.csv',encoding="cp949")

In [3]:
pd.set_option('display.max_columns', None)

# Modifying & Drop columns

In [4]:
df1 = df1.drop(df1.columns[[8,12,18,20,22,23]], axis=1)
df1.head(1)

,발생년,발생년월일시분,주야,요일,사망자수,사상자수,중상자수,경상자수,발생지시도,발생지시군구,사고유형_대분류,사고유형,법규위반_대분류,법규위반,도로형태_대분류,도로형태,가해자_당사자종별,피해자_당사자종별,경도,위도
0,2018,2018-02-14 06:35,주,수,1,1,0,0,서울,서대문구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,126.939274,37.590388

In [5]:
df2 = df2.drop(df2.columns[[2,9,13,20,22,23,24]], axis=1)
df2.rename(columns={"발생년월일시":"발생년월일시분","당사자종별_1당_대분류":"가해자_당사자종별","당사자종별_2당_대분류":"피해자_당사자종별"}, inplace = True)
df2.head(1)

,발생년,발생년월일시분,주야,요일,사망자수,사상자수,중상자수,경상자수,발생지시도,발생지시군구,사고유형_대분류,사고유형,법규위반_대분류,법규위반,도로형태_대분류,도로형태,가해자_당사자종별,피해자_당사자종별,경도,위도
0,2017,2017-01-01 01:00,야간,일,1,2,1,0,전남,장성군,차대차,기타,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,승용차,126.768634,35.294464

In [6]:
df3 = df3.drop(df3.columns[[2,9,13,20,22,23,24]], axis=1)
df3.rename(columns={"발생년월일시":"발생년월일시분","당사자종별_1당_대분류":"가해자_당사자종별","당사자종별_2당_대분류":"피해자_당사자종별"}, inplace = True)

In [7]:
df4 = df4.drop(df4.columns[[8,12,19,21,22,23]], axis=1)
df4.rename(columns={"가해자_당사자종별_대분류":"가해자_당사자종별","피해자_당사자종별_대분류":"피해자_당사자종별"}, inplace = True)

In [8]:
df12=pd.concat([df1,df2],ignore_index=True)
df34=pd.concat([df3,df4],ignore_index=True)
df=pd.concat([df12,df34],ignore_index=True)

In [9]:
df.tail(5)

,발생년,발생년월일시분,주야,요일,사망자수,사상자수,중상자수,경상자수,발생지시도,발생지시군구,사고유형_대분류,사고유형,법규위반_대분류,법규위반,도로형태_대분류,도로형태,가해자_당사자종별,피해자_당사자종별,경도,위도
16283,2015,2015-12-31 06:45,주,목,1,4,3,0,충남,당진시,차량단독,공작물충돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,없음,126.585505,36.851561
16284,2015,2015-12-31 11:05,주,목,1,6,3,2,경북,영천시,차대차,정면충돌,운전자법규위반,안전운전 의무 불이행,단일로,교량위,승용차,화물차,128.946486,35.974254
16285,2015,2015-12-31 15:00,주,목,1,1,0,0,서울,서대문구,차대사람,차도통행중,운전자법규위반,안전운전 의무 불이행,교차로,교차로내,화물차,보행자,126.917914,37.571086
16286,2015,2015-12-31 18:03,야,목,1,1,0,0,충남,서산시,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,126.464905,36.774807
16287,2015,2015-12-31 22:00,야,목,1,1,0,0,충남,천안시,차대사람,기타,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,보행자,127.215562,36.912937

In [10]:
df.shape

(16288, 20)

데이터 중 피해자_당사자종별이 nan인 경우, 없음으로 변경하기

In [11]:
df['피해자_당사자종별']=np.where(df['피해자_당사자종별'].isnull(), '없음', df['피해자_당사자종별'])

# Explore Data

In [12]:
# value_counts = df['발생년'].value_counts(dropna=True, sort=True)
# df_year = value_counts.rename_axis('year').to_frame('counts')
# df_year.to_csv("df_year.csv",encoding='ms949')

In [13]:
df.to_csv("df_all_accident.csv",encoding='ms949')

In [14]:
df['발생지시도'].value_counts()

경기    3026
경북    1767
충남    1418
전남    1404
경남    1391
서울    1348
전북    1105
충북     888
강원     843
부산     605
대구     571
인천     483
광주     372
대전     363
제주     325
울산     300
세종      79
Name: 발생지시도, dtype: int64

# Road data load

In [15]:
df_road=pd.read_csv('road.csv')

In [16]:
df_road=df_road.fillna(0)
df_road['Sum']=df_road['고속국도']+df_road['일반국도']+df_road['지방도']+df_road['시도']+df_road['군도']+df_road['구도']

In [17]:
df_road

,행정구역명,고속국도,일반국도,지방도,시도,군도,구도,Sum
0,서울,27610.0,173120.0,0.0,1029514,0.0,7041672.0,8271916.0
1,부산,68300.0,100782.0,29730.0,823554,155753.0,2193598.0,3371717.0
2,대구,96840.0,144793.0,11604.0,794833,143300.0,1675809.0,2867179.0
3,인천,109480.0,75613.0,42047.0,723792,445225.0,1847820.0,3243977.0
4,광주,26370.0,86569.0,16060.0,575607,0.0,1154429.0,1859035.0
5,대전,76140.0,83887.0,30446.0,499995,0.0,1449920.0,2140388.0
6,울산,70620.0,158565.0,17260.0,455836,628541.0,806232.0,2137054.0
7,세종,18530.0,70961.0,25450.0,244789,0.0,0.0,359730.0
8,경기,826504.0,1616299.0,2389253.0,7647396,462709.0,0.0,12942161.0
9,강원,472020.0,1936332.0,1579191.0,1645641,3133264.0,0.0,8766448.0
10,충북,388406.0,972058.0,1408373.0,1378011,2287296.0,0.0,6434144.0
11,충남,429990.0,1263024.0,1631560.0,2265948,1163794.0,0.0,6754316.0
12,전북,418420.0,1426150.0,1779573.0,1901149,2238754.0,0.0,7764046.0
13,전남,416690.0,1962402.0,2073112.0,1935501,3097588.0,0.0,9485293.0
14,경북,781270.0,2262462.0,2945623.0,2588291,3702070.0,0.0,12279716.0
15,경남,540150.0,1518409.0,2173564.0,3737927,2950827.0,0.0,10920877.0
16,제주,0.0,0.0,690875.0,1480168,696110.0,0.0,2867153.0

# Extent(area) data load

In [18]:
df_extent=pd.read_csv('extent.csv',encoding="cp949")

In [19]:
df_extent

   행정구역명       면적
0     서울    605.2
1     부산    769.9
2     대구    883.5
3     인천   1063.3
4     광주    501.2
5     대전    539.5
6     울산   1061.5
7     세종    464.9
8     경기  10187.8
9     강원  16827.9
10    충북   7407.8
11    충남   8229.2
12    전북   8069.1
13    전남  12343.6
14    경북  19032.9
15    경남  10540.1
16    제주   1850.2

In [20]:
df_extent['Sum/면적']=df_road['Sum']/df_extent['면적']

In [21]:
df_extent

   행정구역명       면적        Sum/면적
0     서울    605.2  13668.070059
1     부산    769.9   4379.422003
2     대구    883.5   3245.250707
3     인천   1063.3   3050.857707
4     광주    501.2   3709.167997
5     대전    539.5   3967.354958
6     울산   1061.5   2013.239755
7     세종    464.9    773.779307
8     경기  10187.8   1270.358762
9     강원  16827.9    520.947236
10    충북   7407.8    868.563406
11    충남   8229.2    820.774316
12    전북   8069.1    962.194792
13    전남  12343.6    768.438138
14    경북  19032.9    645.183656
15    경남  10540.1   1036.126507
16    제주   1850.2   1549.644903

 # 서울 data load

In [22]:
df

,발생년,발생년월일시분,주야,요일,사망자수,사상자수,중상자수,경상자수,발생지시도,발생지시군구,사고유형_대분류,사고유형,법규위반_대분류,법규위반,도로형태_대분류,도로형태,가해자_당사자종별,피해자_당사자종별,경도,위도
0,2018,2018-02-14 06:35,주,수,1,1,0,0,서울,서대문구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,126.939274,37.590388
1,2018,2018-09-02 05:23,야,일,1,1,0,0,서울,용산구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,교차로,교차로횡단보도내,승용차,보행자,126.971732,37.549508
2,2018,2018-12-15 22:35,야,토,1,1,0,0,서울,성북구,차량단독,공작물충돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,이륜차,없음,127.012552,37.591659
3,2018,2018-08-23 11:30,주,목,1,1,0,0,서울,강북구,차량단독,기타,운전자법규위반,기타(운전자법규위반),단일로,기타단일로,승합차,없음,127.024227,37.631240
4,2018,2018-07-16 00:50,야,월,1,1,0,0,서울,강북구,차대사람,기타,운전자법규위반,안전운전 의무 불이행,교차로,교차로횡단보도내,화물차,보행자,127.019590,37.622794
5,2018,2018-12-30 04:19,야,일,1,1,0,0,서울,강북구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,127.022115,37.612366
6,2018,2018-01-29 07:17,주,월,1,1,0,0,서울,광진구,차대사람,횡단중,운전자법규위반,신호위반,단일로,기타단일로,화물차,보행자,127.083241,37.539499
7,2018,2018-05-11 04:47,야,금,1,1,0,0,서울,마포구,차대사람,횡단중,운전자법규위반,과속,단일로,기타단일로,승용차,보행자,126.952724,37.546465
8,2018,2018-04-24 23:50,야,화,1,1,0,0,서울,영등포구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,126.907996,37.519398
9,2018,2018-02-04 07:07,주,일,1,1,0,0,서울,영등포구,차대사람,횡단중,운전자법규위반,신호위반,교차로,교차로내,승합차,보행자,126.897648,37.500264
10,2018,2018-11-29 04:18,야,목,1,1,0,0,서울,성동구,차대사람,기타,운전자법규위반,과속,단일로,기타단일로,승용차,보행자,127.046638,37.551965
11,2018,2018-06-17 11:05,주,일,1,1,0,0,서울,성동구,차대차,기타,운전자법규위반,안전운전 의무 불이행,교차로,교차로부근,자전거,자전거,127.032636,37.540814
12,2018,2018-01-04 14:20,주,목,1,1,0,0,서울,동작구,차대사람,기타,운전자법규위반,안전운전 의무 불이행,기타,기타,화물차,보행자,126.925289,37.501456
13,2018,2018-02-06 12:00,주,화,1,1,0,0,서울,동작구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,교차로,교차로횡단보도내,승용차,보행자,126.937415,37.504715
14,2018,2018-08-04 21:30,야,토,1,1,0,0,서울,중랑구,차대사람,보도통행중,운전자법규위반,신호위반,단일로,기타단일로,자전거,보행자,127.087137,37.590466
15,2018,2018-08-09 10:55,주,목,1,1,0,0,서울,관악구,차대사람,차도통행중,운전자법규위반,안전운전 의무 불이행,교차로,교차로내,화물차,보행자,126.918034,37.475552
16,2018,2018-03-17 08:00,주,토,1,4,3,0,서울,강남구,차대차,추돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,특수차,127.048631,37.529357
17,2018,2018-07-19 03:20,야,목,1,1,0,0,서울,강남구,차대차,추돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,건설기계,127.035767,37.528713
18,2018,2018-09-18 19:30,야,화,1,1,0,0,서울,강서구,차대사람,횡단중,운전자법규위반,신호위반,교차로,교차로내,승합차,보행자,126.869331,37.548645
19,2018,2018-01-19 07:18,주,금,1,1,0,0,서울,송파구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,127.105509,37.517627
20,2018,2018-04-15 02:12,야,일,1,4,0,3,서울,송파구,차대사람,기타,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,127.105304,37.526315
21,2018,2018-08-22 03:50,야,수,1,1,0,0,서울,송파구,차량단독,공작물충돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,이륜차,없음,127.119461,37.506613
22,2018,2018-12-18 22:10,야,화,1,1,0,0,서울,구로구,차대사람,보도통행중,운전자법규위반,보행자 보호의무 위반,교차로,교차로횡단보도내,승합차,보행자,126.885986,37.498681
23,2018,2018-05-03 05:31,야,목,1,4,0,3,서울,서초구,차대차,추돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,화물차,127.007544,37.516132
24,2018,2018-05-17 01:37,야,목,1,1,0,0,서울,양천구,차대차,측면충돌,운전자법규위반,안전운전 의무 불이행,교차로,교차로내,승용차,이륜차,126.880048,37.542185
25,2018,2018-06-19 19:20,야,화,1,1,0,0,서울,도봉구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승합차,보행자,127.043657,37.669407
26,2018,2018-09-10 12:10,주,월,1,1,0,0,서울,은평구,차대사람,기타,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,보행자,126.932268,37.615069
27,2018,2018-01-01 19:17,야,월,1,1,0,0,서울,은평구,차대사람,길가장자리구역통행중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승합차,보행자,126.922186,37.617715
28,2018,2018-09-20 23:50,야,목,1,1,0,0,서울,강남구,차대사람,기타,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승합차,보행자,127.029808,37.493590
29,2018,2018-01-08 13:08,주,월,1,1,0,0,서울,강남구,차대사람,기타,운전자법규위반,보행자 보호의무 위반,단일로,기타단일로,승용차,보행자,127.055003,37.489316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16258,2015,2015-12-30 00:50,야,수,1,2,1,0,충북,진천군,차량단독,전도전복,운전자법규위반,안전운전 의무 불이행,교차로,교차로내,승용차,없음,127.477038,36.927185
16259,2015,2015-12-30 00:50,야,수,1,1,0,0,경남,창원시(통합),차대사람,길가장자리구역통행중,운전자법규위반,안전운전 의무 불이행,교차로,교차로부근,화물차,보행자,128.577871,35.233698
16260,2015,2015-12-30 01:59,야,수,1,4,3,0,부산,연제구,차량단독,공작물충돌,운전자법규위반,안전운전 의무 불이행,교차로,교차로부근,승용차,없음,129.083770,35.171884
16261,2015,2015-12-30 02:11,야,수,1,1,0,0,서울,중랑구,차량단독,전도전복,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,없음,127.125255,37.601355
16262,2015,2015-12-30 02:53,야,수,1,8,3,4,대전,유성구,차대차,측면충돌,운전자법규위반,신호위반,교차로,교차로내,승용차,승용차,127.320495,36.304448
16263,2015,2015-12-30 03:06,야,수,1,1,0,0,서울,도봉구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,교차로,교차로내,화물차,보행자,127.045528,37.680573
16264,2015,2015-12-30 05:15,야,수,1,1,0,0,서울,강동구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,횡단보도상,화물차,보행자,127.132090,37.536100
16265,2015,2015-12-30 05:30,야,수,1,1,0,0,경기,이천시,차대사람,기타,운전자법규위반,안전운전 의무 불이행,기타/불명,기타/불명,승합차,보행자,127.378206,37.293383
16266,2015,2015-12-30 06:15,주,수,1,5,3,0,광주,북구,차대차,기타,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,승용차,126.881737,35.175155
16267,2015,2015-12-30 08:10,주,수,1,1,0,0,경기,부천시,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승합차,보행자,126.784531,37.485518
16268,2015,2015-12-30 08:40,주,수,1,1,0,0,경북,안동시,차대차,측면충돌,운전자법규위반,직진 및 우회전차의 통행방해,교차로,교차로내,승용차,이륜차,128.710023,36.571217
16269,2015,2015-12-30 10:35,주,수,1,1,0,0,부산,북구,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승합차,보행자,129.002505,35.209525
16270,2015,2015-12-30 10:50,주,수,1,1,0,0,경북,김천시,차량단독,전도전복,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,건설기계,없음,128.176417,36.044583
16271,2015,2015-12-30 13:24,주,수,1,5,2,2,전남,담양군,차대차,기타,운전자법규위반,안전거리 미확보,단일로,기타단일로,승용차,승용차,126.972981,35.222616
16272,2015,2015-12-30 14:15,주,수,2,2,0,0,충북,음성군,차량단독,기타,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,없음,127.653986,37.005982
16273,2015,2015-12-30 17:50,주,수,1,1,0,0,전북,김제시,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,보행자,126.954769,35.855710
16274,2015,2015-12-30 18:05,야,수,1,2,0,1,서울,송파구,차대사람,차도통행중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,원동기장치자전거,보행자,127.094287,37.498020
16275,2015,2015-12-30 18:47,야,수,1,1,0,0,경기,양평군,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,보행자,127.538598,37.426123
16276,2015,2015-12-30 18:00,야,수,1,1,0,0,전남,화순군,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,보행자,126.981652,35.059597
16277,2015,2015-12-30 18:03,야,수,1,1,0,0,경북,칠곡군,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,128.537547,36.065388
16278,2015,2015-12-30 19:48,야,수,1,1,0,0,강원,강릉시,차대사람,횡단중,운전자법규위반,보행자 보호의무 위반,단일로,횡단보도상,화물차,보행자,128.822064,37.709305
16279,2015,2015-12-30 21:20,야,수,1,2,0,1,경기,용인시,차대차,정면충돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,화물차,127.202795,37.179144
16280,2015,2015-12-30 22:20,야,수,1,1,0,0,경북,경산시,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,횡단보도상,승용차,보행자,128.737539,35.808670
16281,2015,2015-12-31 00:05,야,목,1,2,1,0,충남,당진시,차량단독,전도전복,운전자법규위반,안전운전 의무 불이행,교차로,교차로부근,화물차,없음,126.593982,36.963863
16282,2015,2015-12-31 00:20,야,목,1,7,4,2,전남,무안군,차량단독,공작물충돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,없음,126.487681,34.999494
16283,2015,2015-12-31 06:45,주,목,1,4,3,0,충남,당진시,차량단독,공작물충돌,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,없음,126.585505,36.851561
16284,2015,2015-12-31 11:05,주,목,1,6,3,2,경북,영천시,차대차,정면충돌,운전자법규위반,안전운전 의무 불이행,단일로,교량위,승용차,화물차,128.946486,35.974254
16285,2015,2015-12-31 15:00,주,목,1,1,0,0,서울,서대문구,차대사람,차도통행중,운전자법규위반,안전운전 의무 불이행,교차로,교차로내,화물차,보행자,126.917914,37.571086
16286,2015,2015-12-31 18:03,야,목,1,1,0,0,충남,서산시,차대사람,횡단중,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,승용차,보행자,126.464905,36.774807
16287,2015,2015-12-31 22:00,야,목,1,1,0,0,충남,천안시,차대사람,기타,운전자법규위반,안전운전 의무 불이행,단일로,기타단일로,화물차,보행자,127.215562,36.912937

In [23]:
df_seoul=df[df['발생지시도']=='서울']
df_seoul = df_seoul.drop(df_seoul.columns[[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17]], axis=1)
df_seoul.head()

   사망자수          경도         위도
0     1  126.939274  37.590388
1     1  126.971732  37.549508
2     1  127.012552  37.591659
3     1  127.024227  37.631240
4     1  127.019590  37.622794

In [24]:
df_seoul.to_csv("df_seoul.csv",header=['dead','lon','lat'],encoding='ms949',index=False)